name: "Create new environment"
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: an-environment-that-doesnt-exist-yet
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
